### ISSUE TITLE
Type inference returns empty cells  if VARCHAR and Number mixed

### ISSUE THREAD

**Issue by zergar** [polydbms/sheetreader-duckdb#53]
Take the following sample file:

| col1 | col2 | col3 |
| ---- | ---- | ---- |
| 1    | \-   | 1    |
| 2    | 1    | 2    |
| 3    | 2    | \-   |
| 4    | \-   | 3    |
| 5    | 3    | \-   |

[test.xlsx](https://github.com/user-attachments/files/17342181/test.xlsx)

Right now, when loading sheetreader produces the following output:

```
D select * from sheetreader('test.xlsx');
┌────────┬─────────┬────────┐
│  col1  │  col2   │  col3  │
│ double │ varchar │ double │
├────────┼─────────┼────────┤
│    1.0 │ -       │    1.0 │
│    2.0 │         │    2.0 │
│    3.0 │         │        │
│    4.0 │ -       │    3.0 │
│    5.0 │         │        │
└────────┴─────────┴────────┘
D 

```

I would expect at least for the second column to get numbers as string values. Instead, I get empty cells.

**Comment by freddie-freeloader** [comment]
Hey @zergar ,

There is an option called `coerce_to_string` and its default value is `false`.

You can read more about it here:
https://github.com/polydbms/sheetreader-duckdb?tab=readme-ov-file#parameters

Note: If you start with a number as the first cell, the extension might infer `DOUBLE` as the type of the column, and you may need to manually specify the type of the column as `VARCHAR` with the `types` option.

If this doesn't work for you, you would propose a different default behavior, let me know -- otherwise, please close the issue. 🙂

**Comment by freddie-freeloader** [comment]
Feel free to open the issue again if you have any further issues with this.
