### ISSUE TITLE
Feature request:  clean column names

### ISSUE THREAD

**Issue by kylelundstedt** [polydbms/sheetreader-duckdb#54]
Great work on the new (and more logically) named extension for reading in Excel files!!!

As a recovering R coder, I've used the R package [janitor](https://cran.r-project.org/web/packages/janitor/vignettes/janitor.html), which offers similar functions to `sheetreader` for reading in "cleaned up" Excel files.  For example, its `clean_names` function will take the header row from an Excel worksheet, and it:

> - Parses letter cases and separators to a consistent format.
> - Default is to snake_case, but other cases like camelCase are available
> - Handles special characters and spaces, including transliterating characters like œ to oe.
> - Appends numbers to duplicated names
> - Converts “%” to “percent” and “#” to “number” to retain meaning
> - Spacing (or lack thereof) around numbers is preserved

My specific request for `sheetreader-duckdb` is the need for a `clean_names` equivalent in `sheetreader` to **convert horrible Excel header names into nicely-formatted DuckDB columns names**.  

The ability to clean column names on import is particularly useful; my experience has been that it is really clunky to rename a large number of DuckDB columns post-import.

**Comment by freddie-freeloader** [comment]
Hey @kylelundstedt,

Thank you for checking out the `sheetreader` extension.

`janitor` looks like a great tool. It seems to utilize `readxl` for parsing XLSX-fields and seems in general more focused on cleaning the column names of data frames in general.

I think it would make more sense to have another DuckDB-extension that is responsible for this, so other *parsers* / *importer functions* / *table functions* can benefit from it.

Unfortunately, `janitor` seems to be implemented in pure R, so it seems that we cannot easily reuse the implementation.

I'd see it as `sheetreader`'s responsibility to import the headers as **intact** as possible, so that a potential `janitor`-like extension can use these with no loss of information (if possible).

Let me know if you are having encoding-issues when it comes to headers, though. 🙂

**Comment by kylelundstedt** [comment]
Totally understand the philosophy, @freddie-freeloader.  I was kinda hoping that `sheetreader` would become more like DuckDB's `read_csv` in terms of comprehensive functionality.  That said, thanks so much for the package!
